### ISSUE TITLE
探索CSS Reset优化之路

### ISSUE THREAD

**Issue by XfLoops** [lezhixing/blog#1]
> ## 摘要:speaking_head:
> 
> 本文分为两个部分：
> 
>    一、介绍当下流行的CSS Reset做法。包括1.使用标准化库 2.定制CSS Reset 3.使用Universal Selector  ，并评价了每类做法的优点和缺点。
> 
>    二、对比了6种CSS Reset。选用百度，淘宝，微博，京东等网站的CSS Reset，HTML5-Reset CSS，以及公司的lzx.base，从10个小方面进行对比，指出lzx.base跟其他做法存在的差异。
## 目录:point_down:
1. <a href="#t1">流行的CSS重置做法</a>
   
   1.1 <a href="#t1-1">使用标准化库</a>
   - 1.1.1 <a href="#t1-1-1">Normalize.css和Sanitize.css</a>
   - 1.1.2 <a href="#t1-1-2">使用标准化库的优点和缺点</a>
   
   1.2 <a href="#t1-2">定制CSS Reset</a>
   - 1.2.1 <a href="#t1-2-1">Yahoo! (YUI 3)</a>
   - 1.2.2 <a href="#t1-2-2">Eric Meyer CSS Reset</a>
   - 1.2.3 <a href="#t1-2-3">HTML5-Reset  **VS**  html5doctor</a>
   
   1.3 <a href="#t1-3">使用Universal Selector \* </a>
2. <a href="#t2">流行库的CSS重置做法</a>
3. <a href="#t3">国内公司的CSS重置做法</a>
   
   3.1 <a href="#t3-1">重置margin和padding</a>
   
   3.2 <a href="#t3-2">设置字体</a>
   
   3.3 <a href="#t3-3">设置h1 -h6</a>
   
   3.4 <a href="#t3-4">设置列表元素ol,ul</a>
   
   3.5 <a href="#t3-5">设置超链接 a</a>
   
   3.6 <a href="#t3-6">设置控件</a>
   
   3.7 <a href="#t3-7">设置表格table</a>
   
   3.8 <a href="#t3-8">设置图片img</a>
   
   3.9 <a href="#t3-9">设置辅助元素small, sub,sup等</a>
   
   3.10 <a href="#t3-10">设置伪类，:after,:before</a>
4. <a href="#t4">一些CSS重置的观点</a>
5. <a href="#t5">总结</a>
6. <a href="#t6">参考资料</a>
## **TL;DR;**

![css reset](http://red-team-design.com/dist/uploads/2010/11/css-reset.png)

CSS reset的作用是让各个浏览器的CSS样式有一个统一的基准。最早的一份CSS reset来自Tantek 的[undohtml.css](http://tantek.com/log/2004/undohtml.css)，其余一些有名的CSS reset如业界领袖Eric Meyer的[CSS Reset](http://meyerweb.com/eric/tools/css/reset/)，或是[Tripoli Reset](http://monc.se/kitchen/124/introducing-tripoli)。

<h2 id="t1">1. 流行的CSS重置做法</h2>

[cssreset.com](http://cssreset.com/)列出了“2016’s most popular CSS Reset scripts”，如下：
- Normalize.css 1.0
- Eric Meyer’s “Reset CSS” 2.0
- HTML5 Doctor CSS Reset
- Yahoo! (YUI 3) Reset CSS
- Universal Selector \* Reset

上述CSS重置的做法可以分成三类来介绍：
1. 使用标准化库
2. 定制CSS Reset
3. 使用Universal Selector`*`

<h3 id="t1-1"> 1.1 使用标准化库</h3>

> 统计数据截至2016-10-19

| Name | GitHub Stars  :octocat: | Related Projects | Author | Last commit |
| :-: | :-: | :-: | :-: | :-: |
| [Normalize.css](http://necolas.github.io/normalize.css/) | 23198 | Twitter, GitHub, Bootstrap, HTML5 Boilerplate... | [Nicolas Gallagher](http://nicolasgallagher.com/),[Jonathan Neal](http://music.thewikies.com/jonneal/) | 14 days ago |
| [Sanitize.css](https://jonathantneal.github.io/sanitize.css/) | 2018 | 未知 | [Jonathan Neal](http://music.thewikies.com/jonneal/) | 14 days ago |

<h4 id="t1-1-1"> 1.1.1 Normalize.css和Sanitize.css</h4>
-   Normalize.css:fire::fire::fire:
  
  Normalize是两位作者在广泛调研的基础上，总结了各个浏览器默认样式之间的差别，旨在消除这一差别而创作的产物。Normalize注重解决浏览器默认样式的一致性，使得CSS文件在不同的浏览器中能够得到一致的效果。Normalize保留有用的默认样式。
-   Sanitize.css
  
  Normalize的作者之一创作。跟Normalize一样，除了解决浏览器间的差异，还遵循了CSS最佳实践的做法，这些做法跟[Paul Irish](https://twitter.com/paul_irish)和[Chris Coyier](https://twitter.com/chriscoyier)两位大牛所提倡的最佳实践保持一致。
-   Normalize.css VS Sanitize.css
  
  Sanitize.css跟Normalize.css相比，增加了CSS最佳实践。

<h4 id="t1-1-2"> 1.1.2 使用标准化库的优点和缺点</h4>

-   优点:+1:
  
  Normalize 相对平和，注重通用的方案，重置掉该重置的样式，保留有用的 user agent 样式，同时修复了一些浏览器的bug。
-   缺点:-1:
  
    Normalize的重置库解决的样式差异多而全，涵盖桌面端和移动端，但这对于项目来说不一定是必需的。例如，包含很多对低版本浏览器的hack，如果没必要支持低版本浏览器，那么Normalize的重置库则会有很多冗余样式，一定程度上增加了CSS文件大小。

<h3 id="t1-2"> 1.2 定制CSS Reset</h3>

定制CSS Reset跟使用Normalize最大的不同是，它只解决一部分元素的样式差异。

这里分两成大阵营来介绍：**Yahoo! (YUI 3)** 和 **Eric Meyer CSS Reset**

<h4 id="t1-2-1"> 1.2.1 Yahoo! (YUI 3)</h4>

> 统计数据截至2016-10-19

| Name | GitHub Stars:octocat: | Last commit |
| :-: | :-: | :-: |
| [Yahoo! (YUI 3)](https://github.com/yui/yui3) | 3448 | 2 years ago |

​ Yahoo! 早年红极一时，[YUI](http://yuilibrary.com/)（Yahoo! User Interface）在2006年出品了YUI2 cssreset，后来又更新到[YUI3 cssreset](https://github.com/yui/yui3/blob/master/build/cssreset/cssreset.css)。近些年Yahoo! 逐渐走向没落:thinking:，YUI 官网宣称不再去维护YUI 3 了:warning:。github上YUI 3的最后一次提交也还是在2014年。YUI3 cssreset也被弃用，转而投向Normalize.css。

<h4 id="t1-2-2"> 1.2.2 Eric Meyer CSS Reset</h4>

业界领袖Eric Meyer [CSS Reset](http://meyerweb.com/eric/tools/css/reset/)最受追捧:sparkles:。他本人也明确指出，不要直接拿来用，而要在此基础上做一些修改后用。

Richard Clark在 Eric Meyer CSS Reset 的基础上，移除了一些被弃用的标签，新增了HTML5标签，形成 [html5doctor CSS Reset](./html5doctor.css)。

HTML5-Reset在借鉴Eric Meyer CSS Reset 、html5doctor CSS Reset、HTML5 Boilerplate(注：该项目使用的是normalize.css的修改版) 的基础上，形成了HTML5-Reset CSS Reset。

> 统计数据截至2016-10-19

| Project Name | GitHub Stars :octocat: | Author | Last Commit |
| :-: | :-: | :-: | :-: |
| [HTML5-Reset](https://github.com/murtaugh/HTML5-Reset) | 1924 | Tim Murtaugh | 12days ago |

 基于Eric Meyer CSS Reset进行修改形成的CSS Reset 还有很多其他版本。感兴趣的话可以进一步阅读：[The History of CSS Resets](http://sixrevisions.com/css/the-history-of-css-resets/)

<h4 id="t1-2-3"> 1.2.3 HTML5-Reset  VS  html5doctor</h4>

html5doctor没有专门针对个别浏览器的样式hack。而HTML5-Reset则含有，区别包括：
- HTML5-Reset给所有元素加上了`box-sizing:border-box`
- HTML5-Reset CSS 增加`img`,`object`,`embed`元素的自适应： `max-width:100%`
- HTML5-Reset CSS 修复了个别元素在IE, Chrome浏览器的样式问题

<h3 id="t1-3"> 1.3 使用Universal Selector * </h3>

使用全局选择器`*`对样式进行重置，这种做法不值得提倡。例如：

``` css
* {
    vertical-align: baseline;
    font-family: inherit;
    font-style: inherit;
    font-size: 100%;
    border: none;
    padding: 0;
    margin: 0;  
    }
```

 这会让所有的元素都会重置`padding`,`margin`为0，不仅影响了一些不必要进行重置的元素，而且也让CSS的渲染变得低效。

<h2 id="t2"> 2. 流行库的CSS重置做法</h2>

一些流行的库，如[SUI](http://sui.taobao.org/sui/docs/index.html), [Boostrap.css](https://github.com/twbs/bootstrap)，[Semantic-UI](https://github.com/Semantic-Org/Semantic-UI)等都直接或者间接地引用Normalize.css。

<h2 id="t3"> 3. 国内公司的CSS重置做法</h2>

选取了baidu, taobao, jd,weibo四家网站的首页，摘取了各自网站reset css部分，并对比HTML5 Reset CSS(以下简称HTML5-Reset)和lzx.base.css(以下简称lzx-base)，分析如下。

<h4 id="t3-1"> 3.1 重置margin和padding</h4>

- 重置方法

大多数reset都会对元素的`margin,padding`进行重置，分为两种方法。第一种如下，baidu, taobao, jd,weibo,lzx-base都是这种做法：

``` css
{
    margin: 0;
    padding: 0;
}
```

第二种是HTML5-Reset所使用的方法：

``` css
{
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font-weight: normal;
    vertical-align: baseline;
    background: transparent;
}
```
- 重置元素

weibo,baidu,taobao,jd,HTML5-Reset 的Reset CSS共同的部分包括：`body` , `h1-h6`, `dd,dl,dt`, `ol,ul,li`, `form,fieldset,legend`, `input, textarea`, `th,td`, `pre`
- 对比lzx-base

lzx-base缺少了对`form,fieldset,legend`,  `pre`的重置。相对而言，lzx-base跟 baidu, taobao比较相像。

<h4 id="t3-2"> 3.2 设置字体</h4>

baidu,jd,weibo,HTML5-Reset都没有设置字体,只有taobao设置了字体，如下：

``` css
body,
button,
input,
select,
textarea {
   font: 12px/1.5 tahoma,arial,'Hiragino Sans GB','\5b8b\4f53',sans-serif
}
```

跟lzx-base相同。

<h4 id="t3-3"> 3.3 设置h1 -h6 </h4>

6套reset css都对h1-h6进行了重置。但重置方式有些不同，如下：
- weibo

``` css
h1,
h2,
h3,
h4,
h5,
h6 {
    font-size: 100%;
    font-weight: normal;
}
```
- baidu, taobao,

``` css
h1,
h2,
h3,
h4,
h5,
h6 {
    font-size: 100%;
}
```
- lzx-base

``` css
h1 {
    font-size: 20px;
}
h2 {
    font-size: 18px;
}
h3 {
    font-size: 16px;
}
h4,
h5,
h6 {
    font-size: 100%;
}
```

<h4 id="t3-4"> 3.4 设置列表元素ol,ul </h4>

全部的reset css都对 `ul,ol` 有如下重置：

``` css
ul,
ol {
    list-style: none;
}
```

<h4 id="t3-5"> 3.5 设置超链接 a </h4>

各个reset css对`a` 的处理不太一样，如下：
- weibo

``` css
a:focus {
    outline-style: none;
}
```
- baidu, taobao

``` css
a {
    text-decoration: none;
}
a:hover {
    text-decoration: underline;
}
```
- HTML5-Reset

``` css
a {
    margin: 0;
    padding: 0;
    font-size: 100%;
    vertical-align: baseline;
    background: transparent;
}
```
- lzx-base

``` css
a {
    text-decoration: none;
    color: #535353;
}
a:hover {
    text-decoration: none;
}
a:active,
a:hover {
    outline: 0;
}
```

<h4 id="t3-6"> 3.6 设置控件</h4>

这里的控件包括：`button,input,select,textarea`。
- weibo

``` css
input,
textarea,
select {
    font-family: inherit;
    font-size: inherit;
    font-weight: inherit;
    *font-size: 100%;
}
textarea {
    resize: none;
}
input::-ms-clear {
    display: none;
}
```
- baidu

``` css
button,
input,
select,
textarea {
    font-size: 100%;
}
textarea {
    resize: vertical;
}
```
- jd

``` css
button,
html input[type=button],
input[type=submit] {
    -webkit-apperance: button;
    cursor: pointer;
}

button[disabled],
html input[disabled] {
    cursor: default
}
```
- HTML5-Reset

``` css
input,
select {
    vertical-align: middle;
}
input[type="radio"] {
    vertical-align: text-bottom;
}
input[type="checkbox"] {
    vertical-align: bottom;
}
.ie7 input[type="checkbox"] {
    vertical-align: baseline;
}
.ie6 input {
    vertical-align: text-bottom;
}
select,
input,
textarea {
    font: 99% sans-serif;
}
label,
input[type=button],
input[type=submit],
input[type=file],
button{
    cursor: pointer;
}
/* Webkit browsers add a 2px margin outside the chrome of form elements */
button,
input,
select,
textarea {
    margin: 0;
}
/* make buttons play nice in IE */
button,
input[type=button] {
    width: auto; overflow: visible;
}
```
- taobao, lzx-base

``` css
button,
input,
select,
textarea {
    font-size: 100%;
}
```

<h4 id="t3-7"> 3.7 设置表格table </h4>

- weibo,baidu,taobao,lzx-base

``` css
table {
    border-collapse: collapse;
    border-spacing: 0;
}
```
- HTML5-Reset

``` css
/* tables still need cellspacing="0" in the markup */
table {
    border-collapse: separate;
    border-spacing: 0;
}
th {
    font-weight: bold;
    vertical-align: bottom;
}
td {
    font-weight: normal;
    vertical-align: top;
}
table {
    font-size: inherit;
    font: 100%;
}
```

<h4 id="t3-8"> 3.8 设置图片img</h4>

- baidu

``` css
img {
      border: 0;
    -ms-interpolation-mode: bicubic;
}
```
- jd

``` css
img {
    border: 0;
    vertical-align: middle;
}
```
- HTML5-Reset

``` css
/* Responsive images and other embedded objects */
/* if you don't have full control over `img` tags (if you have to overcome attributes), consider adding height: auto */
img {
    vertical-align: top;
    max-width: 100%;
}
```
- weibo, taobao, lzx-base

``` css
img {
    border: 0;
}
```

<h4 id="t3-9"> 3.9 设置辅助元素small, sub,sup等</h4>

每套reset css中包含的辅助元素各不相同。
- weibo，含`address,caption,cite,code,dfn,em,th,var,i,sup,sub,abbr,acronym`

``` css
address,
caption,
cite,
code,
dfn,
em,
th,
var,
i {
    font-style: normal;
    font-weight: normal;
}
sup {
    vertical-align: text-top;
}
sub {
    vertical-align: text-bottom;
}
abbr,
acronym {
    border: 0;
    font-variant: normal;
}
```
- baidu,含`em,small`，设置如下：

``` css
em {
    font-style: normal;
}
small {
    font-size: 12px;
}
```
- taobao,含`address,cite,dfn,em,var,code,kbd,pre,samp ,small,sub,sup`，设置如下：

``` css
address,
cite,
dfn,
em,
var {
    font-style: normal;
}
code,
kbd,
pre,
samp {
    font-family: courier new,courier,monospace;
}
small {
    font-size: 12px;
}
sup {
    vertical-align: text-top;
}
sub {
    vertical-align: text-bottom;
}
```
- jd, 含`hr,em,i,u`，设置如下：

``` css
hr {
    -moz-box-sizing: content-box;
    box-sizing: content-box;
    height: 0;
}
em,
i,
u {
    font-style: normal;
}
```
- HTML5-Reset，含`hr,pre, small,stong,sub,sup,code, kbd, samp`

``` css
hr {
    display: block;
    height: 1px;
    border: 0;
    border-top: 1px solid #ccc;
    margin: 1em 0;
    padding: 0;
}
pre {
    white-space: pre; /* CSS2 */
    white-space: pre-wrap; /* CSS 2.1 */
    white-space: pre-line; /* CSS 3 (and 2.1 as well, actually) */
    word-wrap: break-word; /* IE */
}
small {
    font-size: 85%;
}
strong {
    font-weight: bold;
}
/* Make sure sup and sub don't mess with your line-heights http://gist.github.com/413930 */
sub,
sup {
    font-size: 75%;
    line-height: 0;
    position: relative;
}
sup {
    top: -0.5em;
}
sub {
    bottom: -0.25em;
}
/* standardize any monospaced elements */
pre,
code,
kbd,
samp {
    font-family: monospace, sans-serif;
}
```
- lzx-base，只含: `small` ,设置如下：

``` css
small {
    font-size: 12px;
}
```

<h4 id="t3-10"> 3.10 设置伪类，:after,:before</h4>

这里的伪类不包括清除浮动的设置。
- lzx.base ，baidu, taobao, jd： 没有设置伪类的样式。
- weibo

``` css
q:before,
q:after {
    content: '';
}
```
- HTML5-Reset

``` css
blockquote:before,
blockquote:after,
q:before,
q:after {
    content: '';
    content: none;
}
```

<h2 id="t4"> 4. 一些CSS重置的观点</h2>
- 张鑫旭:speaking_head:  
  
  > 我个人是比较讨厌这类冗余的CSS reset，绝大多数是浪费代码，浪费性能。我认为CSS reset这个概念应该淘汰。[查看出处](http://www.zhangxinxu.com/wordpress/2010/04/css-reset%E7%9A%84%E9%87%8D%E6%96%B0%E5%AE%A1%E8%A7%86-%E9%81%BF%E5%85%8D%E6%A0%B7%E5%BC%8F%E9%87%8D%E7%BD%AE/)
- 贺师俊:speaking_head:
  
  > 最初出现 CSS reset 的目的是解决浏览器在默认样式上的诸多差异和问题。而现代浏览器在这方面的差异已经小了很多，所以 CSS reset 的必要性就不那么高了。[查看出处](https://www.zhihu.com/question/23554164)

<h2 id="t5"> 5. 总结:thinking:</h2>

Normalize在消除浏览器间的样式差异，及修复浏览器的样式bug方面，做的工作比较多。Reset CSS 则只针对部分元素的样式进行重置，因为所考虑的兼容浏览器不同，因而各有各的特点。Universal Selector由于会造成过度的重置，并且影响性能，不是一种明智的做法。几大互联网公司的Reset CSS虽有差别，但也有共性的地方，这些共性的地方从侧面体现了CSS的最佳实践，是值得借鉴的。

<h2 id="t6"> 6. 参考资料：</h2>

1. [The History of CSS Reset](http://sixrevisions.com/css/the-history-of-css-resets/)
2. [A Comprehensive Guide to CSS Resets](http://sixrevisions.com/css/a-comprehensive-guide-to-css-resets/)
3. [Should You Reset Your CSS?](http://sixrevisions.com/css/should-you-reset-your-css/)
4. [CSS: reset or normalize?](https://the-pastry-box-project.net/oli-studholme/2013-june-3)
5. [Reset Reasoning](http://meyerweb.com/eric/thoughts/2007/04/18/reset-reasoning)
6. [About normalize.css](http://nicolasgallagher.com/about-normalize-css/)

工具：
1. 查看浏览器默认样式，包括IE,Chrome,Firefox,Safari: [http://www.iecss.com/](http://www.iecss.com/)
2. 查看页面使用不同的重置库产生的效果：[cssresetr](https://perishablepress.com/cssresetr/)
